version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout

      # Use cache for dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Run build
      - run: yarn build

      # Run tests
      - run: yarn test

      # Run coverage
      - run: yarn codecov

      # Store node_modules
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  deploy-preview:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - attach_workspace:
          at: /home/circleci
      # Run Deploy Preview if PR
      - run:
          name: Deploy Preview
          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi

  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - attach_workspace:
          at: /home/circleci

      - setup_remote_docker:
          docker_layer_caching: true

      # Push welcome-app to Dockerhub
      - run:
          name: Deploy Welcome Application to DockerHub
          command: yarn wa:deploy

      # Publish libs
      - run:
          name: Publish Libs
          command: yarn publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-preview:
          requires:
            - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
